on: push

name: Test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '23.1'
          elixir-version: '1.11.1'
      - run: mix deps.get
      - run: mix test
      - run: mix format --check-formatted
