name: Release

on:
  workflow_run:
    workflows: ["Test"]
    branches: [main]
    types:
      - completed

env:
  APP_NAME: tq2-app
  AWS_CLUSTER_NAME: teiqui
  AWS_DEFAULT_REGION: sa-east-1
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CONTAINER_IMAGE: tq2-app:${{ github.sha }}
  KUBECTL_VERSION: 1.18
  NAMESPACE: production

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Setup ECR
      run: |
        $(aws ecr get-login --no-include-email)

    - name: Build
      run: |
        docker build \
          -t $CONTAINER_IMAGE \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE \
          -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest .

    - name: Push
      if: github.ref == 'refs/heads/master'
      run: |
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest
        docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE

  migrate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Migrate
    needs: build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master

    - name: Setup
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v$KUBECTL_VERSION.0/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Config
      run: |
        aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME

    - name: Migrate
      run: |
        kubectl run ${APP_NAME}-migrate-${GITHUB_SHA}                                      \
        --image=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE \
        --namespace=$NAMESPACE                                                             \
        --overrides="$(cat manifests/pod.json)"                                            \
        --generator=run-pod/v1                                                             \
        --attach                                                                           \
        --rm

  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy
    needs: migrate
    runs-on: ubuntu-latest

    steps:
    - name: Setup
      run: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v$KUBECTL_VERSION.0/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl

    - name: Config
      run: |
        aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME

    - name: Deploy
      run: |
        kubectl set image --record deployment/tq2-app -n $NAMESPACE \
          app=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$CONTAINER_IMAGE

    - name: Verify
      run: |
        kubectl rollout status deployment/tq2-app -n $NAMESPACE
